### PR TITLE
Update tasks.csv

### PR DESCRIPTION
**Pull request by Sulaiman001**
@Rajputusman  review the new changes

### CODE REVIEW

**Comment by RajputUsman** [comment]
@Sulaiman001 Merge into your repo make PR onto the [thenewboston-developers/Payment-Processor](https://github.com/thenewboston-developers/Payment-Processor) and then ask. Also use **Reviewers** column at top right for the review first.

**Comment by Sulaiman001** [comment]
@Rajputusman  For some reasons I can't use the **Reviewers** its not working so I have to just tag you and I don't why

**Comment by RajputUsman** [comment]
Because it your personal repo first merge the changes then make a PR onto the thenewboston-developers/Payment-Processor and then you can use the **Reviewers** column.

**Comment by Sulaiman001** [comment]
Trying to make a PR thenewboston-developers/Payment-Processor seeing an error Merging is Blocked.

**Comment by RajputUsman** [comment]
image
Make a PR you can't merge

**Pull request merged**
