### PR TITLE
Update tasks.csv

### PR DESCRIPTION
**Pull request by Sulaiman001**
@odetolataiwo and @Rajputusman there is a new payment completed by me and has been added to task.csv please review and merge.

### CODE REVIEW

**Review by RajputUsman — CHANGES_REQUESTED** [review]
@Sulaiman001 Some mistakes are there:-
1. Starting letter for the repo of thenewboston-js is small.
2. No column space for PR(Pull Request).
3. Don't add spaces at the beginning of username,date,amount,bounty_status.
(Let me know do you trying to write by github or you are using Microsoft Excel. Checkout some previous commits for the thenewboston-js)

**Comment by Sulaiman001** [comment]
Okay, thanks for the correction I will correct it now, am not using Excel, directly on Github.

**Comment by Sulaiman001** [comment]
@Rajputusman  Have updated it

**Comment by RajputUsman** [comment]
Issue Id for the PR(Pull Request).
Also, copy the contributor name exactly not in lowercase required.

**Comment by Sulaiman001** [comment]
Changed the contributor name to how it is on Github, the issue id is 45.

**Comment by RajputUsman** [comment]
> Changed the contributor name to how it is on Github, the issue id is 45.

That's a PR ID, not an issue ID. Try to ask the reviewer of the PR with which issue that PR is linked.

**Comment by Sulaiman001** [comment]
I did that already he said no issue was created for the task and he did not know that issues are to be created for all tasks, he promise to create one later.

**Comment by RajputUsman** [comment]
Okay once you got that issue ID tag me I will merge your PR.

**Comment by Sulaiman001** [comment]
@Rajputusman  DONE, Please review it

**Review by RajputUsman — CHANGES_REQUESTED** [review]
At 447 line wrong issue ID it is not 49 but 48 for the 45PR.

**Comment by Sulaiman001** [comment]
Sorry about that mistake, have corrected it

**Pull request merged**
